import { Prisma, PrismaClient } from '@prisma/client';
import { AppError } from '../../../shared/domain/AppError.js';
import type { OrdersRepository, ShipmentInput, ShipmentStatusInput } from '../domain/OrdersRepository.js';

const orderInclude = { status: true, items: { include: { store: true } }, addresses: { include: { type: true } }, shippingSelections: { include: { store: true } }, payments: { include: { status: true }, orderBy: { createdAt: 'desc' as const } } } satisfies Prisma.OrderInclude;
const shipmentInclude = { status: true, shippingMethod: { include: { carrier: true } }, warehouse: true, items: { include: { orderItem: true } } } satisfies Prisma.ShipmentInclude;
function mapOrder(order: Prisma.OrderGetPayload<{ include: typeof orderInclude }>) { return { id: order.id, orderNumber: order.orderNumber, status: order.status.code, paymentStatus: order.payments[0]?.status.code ?? 'PENDING', currency: order.currency, totals: { subtotalMinor: Number(order.subtotalMinor), discountMinor: Number(order.discountMinor), shippingMinor: Number(order.shippingMinor), taxMinor: Number(order.taxMinor), totalMinor: Number(order.totalMinor) }, items: order.items.map((item) => ({ id: item.id, storeId: item.storeId, productName: item.productName, sku: item.sku, quantity: item.quantity, unitPriceMinor: Number(item.unitPriceMinor), lineTotalMinor: Number(item.lineTotalMinor), currency: item.currency })), shippingSelections: order.shippingSelections.map((selection) => ({ id: selection.id, store: { id: selection.store.id, slug: selection.store.slug, displayName: selection.store.displayName }, shippingMethodId: selection.shippingMethodId, carrierName: selection.carrierName, methodCode: selection.methodCode, methodName: selection.methodName, serviceLevel: selection.serviceLevel, amountMinor: Number(selection.amountMinor), currency: selection.currency })), addresses: order.addresses.map((address) => ({ type: address.type.code, recipientName: address.recipientName, line1: address.line1, line2: address.line2, cityName: address.cityName, stateName: address.stateName, countryCode: address.countryCode, postalCode: address.postalCode })), placedAt: order.placedAt.toISOString() }; }
function mapShipment(shipment: Prisma.ShipmentGetPayload<{ include: typeof shipmentInclude }>) { return { id: shipment.id, orderId: shipment.orderId, status: shipment.status.code, warehouse: { id: shipment.warehouse.id, code: shipment.warehouse.code, name: shipment.warehouse.name }, carrier: shipment.shippingMethod.carrier.name, shippingMethod: shipment.shippingMethod.name, trackingNumber: shipment.trackingNumber, items: shipment.items.map((item) => ({ orderItemId: item.orderItemId, quantity: item.quantity })), shippedAt: shipment.shippedAt?.toISOString() ?? null, deliveredAt: shipment.deliveredAt?.toISOString() ?? null, createdAt: shipment.createdAt.toISOString() }; }

export class PrismaOrdersRepository implements OrdersRepository {
  constructor(private readonly db: PrismaClient) {}
  async listCustomerOrders(userId: string): Promise<unknown[]> { const rows = await this.db.order.findMany({ where: { userId }, include: orderInclude, orderBy: { createdAt: 'desc' } }); return rows.map(mapOrder); }
  async findCustomerOrder(userId: string, orderId: string): Promise<unknown | null> { const row = await this.db.order.findFirst({ where: { id: orderId, userId }, include: orderInclude }); return row ? mapOrder(row) : null; }
  async cancelOrder(userId: string, orderId: string, reason?: string): Promise<unknown> { return this.db.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: orderId, userId }, include: { status: true } }); if (!order) throw new AppError(404, 'NOT_FOUND', 'Order not found.'); if (order.status.code !== 'PENDING_PAYMENT') throw new AppError(409, 'INVALID_STATE', 'Only unpaid orders can be cancelled through this endpoint.'); const status = await tx.orderStatus.findUniqueOrThrow({ where: { code: 'CANCELLED' } }); await tx.order.update({ where: { id: orderId }, data: { statusId: status.id } }); await tx.orderStatusHistory.create({ data: { orderId, fromStatusId: order.statusId, toStatusId: status.id, changedByUserId: userId, reason } }); const result = await tx.order.findUniqueOrThrow({ where: { id: orderId }, include: orderInclude }); return mapOrder(result); }); }
  async listSellerOrderItems(userId: string): Promise<unknown[]> { const rows = await this.db.orderItem.findMany({ where: { store: { sellerProfile: { userId } } }, include: { order: { include: { status: true } }, store: true }, orderBy: { createdAt: 'desc' } }); return rows.map((row) => ({ id: row.id, orderId: row.orderId, orderNumber: row.order.orderNumber, orderStatus: row.order.status.code, storeId: row.storeId, productName: row.productName, sku: row.sku, quantity: row.quantity, lineTotalMinor: Number(row.lineTotalMinor), currency: row.currency })); }
  async listCustomerShipments(userId: string, orderId: string): Promise<unknown[]> { const order = await this.db.order.findFirst({ where: { id: orderId, userId }, select: { id: true } }); if (!order) throw new AppError(404, 'NOT_FOUND', 'Order not found.'); const rows = await this.db.shipment.findMany({ where: { orderId }, include: shipmentInclude, orderBy: { createdAt: 'asc' } }); return rows.map(mapShipment); }
  async createShipment(userId: string, input: ShipmentInput): Promise<unknown> {
    return this.db.$transaction(async (tx) => {
      const existing = await tx.shipment.findUnique({ where: { orderId_idempotencyKey: { orderId: input.orderId, idempotencyKey: input.idempotencyKey } }, include: shipmentInclude });
      if (existing) return mapShipment(existing);
      const order = await tx.order.findUnique({ where: { id: input.orderId }, include: { status: true, items: true, shippingSelections: true } });
      if (!order) throw new AppError(404, 'NOT_FOUND', 'Order not found.');
      const warehouse = await tx.warehouse.findUnique({ where: { id: input.warehouseId }, include: { store: { include: { sellerProfile: true, status: true } } } });
      if (!warehouse || warehouse.store.sellerProfile.userId !== userId) throw new AppError(403, 'FORBIDDEN', 'You do not own this warehouse.');
      if (!warehouse.isActive || warehouse.store.status.code === 'ARCHIVED') throw new AppError(409, 'INVALID_STATE', 'Warehouse is not available for fulfilment.');
      if (order.status.code !== 'PAID' && order.status.code !== 'PROCESSING') throw new AppError(409, 'INVALID_STATE', 'Only paid orders can be fulfilled.');
      const selection = order.shippingSelections.find((candidate) => candidate.storeId === warehouse.storeId);
      const method = await tx.shippingMethod.findFirst({ where: { id: input.shippingMethodId, ...(selection ? {} : { isActive: true }) } }); if (!method) throw new AppError(404, 'NOT_FOUND', 'Shipping method not found.');
      if (selection && selection.shippingMethodId !== method.id) throw new AppError(422, 'INVALID_SHIPPING_METHOD', 'Shipment method must match the customer-selected shipping method.');
      const orderItems = new Map(order.items.map((item) => [item.id, item]));
      for (const requested of input.items) { const item = orderItems.get(requested.orderItemId); if (!item || item.storeId !== warehouse.storeId || !item.productVariantId) throw new AppError(400, 'INVALID_SHIPMENT_ITEM', 'Shipment item is not fulfilled by this warehouse store.'); const shipped = await tx.shipmentItem.aggregate({ where: { orderItemId: item.id, shipment: { status: { code: { not: 'CANCELLED' } } } }, _sum: { quantity: true } }); if ((shipped._sum.quantity ?? 0) + requested.quantity > item.quantity) throw new AppError(409, 'INVALID_STATE', 'Shipment quantity exceeds the unshipped order quantity.'); }
      const pending = await tx.shipmentStatus.findUniqueOrThrow({ where: { code: 'PENDING' } });
      const shipment = await tx.shipment.create({ data: { orderId: input.orderId, warehouseId: input.warehouseId, shippingMethodId: input.shippingMethodId, orderShippingSelectionId: selection?.id, statusId: pending.id, idempotencyKey: input.idempotencyKey, trackingNumber: input.trackingNumber, items: { create: input.items } }, include: shipmentInclude });
      const reserveType = await tx.inventoryMovementType.findUniqueOrThrow({ where: { code: 'RESERVE' } });
      for (const requested of input.items) { const item = orderItems.get(requested.orderItemId)!; const inventory = await tx.inventory.findUnique({ where: { warehouseId_productVariantId: { warehouseId: input.warehouseId, productVariantId: item.productVariantId! } } }); if (!inventory || inventory.onHandQty - inventory.reservedQty < requested.quantity) throw new AppError(422, 'INSUFFICIENT_INVENTORY', 'Insufficient available inventory for shipment.'); const updated = await tx.inventory.updateMany({ where: { id: inventory.id, version: inventory.version, onHandQty: { gte: inventory.reservedQty + requested.quantity } }, data: { reservedQty: { increment: requested.quantity }, version: { increment: 1 } } }); if (updated.count !== 1) throw new AppError(409, 'INVENTORY_CONFLICT', 'Inventory changed; retry shipment creation.'); await tx.inventoryMovement.create({ data: { inventoryId: inventory.id, typeId: reserveType.id, quantityDelta: 0, reservedDelta: requested.quantity, referenceKey: `shipment:${shipment.id}:reserve:${item.id}`, referenceType: 'SHIPMENT_RESERVATION', referenceId: shipment.id } }); }
      if (order.status.code === 'PAID') { const processing = await tx.orderStatus.findUniqueOrThrow({ where: { code: 'PROCESSING' } }); await tx.order.update({ where: { id: order.id }, data: { statusId: processing.id } }); await tx.orderStatusHistory.create({ data: { orderId: order.id, fromStatusId: order.statusId, toStatusId: processing.id, changedByUserId: userId, reason: 'Shipment created' } }); }
      return mapShipment(shipment);
    });
  }
  async updateShipmentStatus(userId: string, shipmentId: string, input: ShipmentStatusInput): Promise<unknown> {
    return this.db.$transaction(async (tx) => {
      const shipment = await tx.shipment.findUnique({ where: { id: shipmentId }, include: { status: true, order: { include: { status: true } }, warehouse: { include: { store: { include: { sellerProfile: true } } } }, items: { include: { orderItem: true } } } });
      if (!shipment) throw new AppError(404, 'NOT_FOUND', 'Shipment not found.'); if (shipment.warehouse.store.sellerProfile.userId !== userId) throw new AppError(403, 'FORBIDDEN', 'You do not own this shipment.');
      if (shipment.status.code === input.status) { const current = await tx.shipment.findUniqueOrThrow({ where: { id: shipmentId }, include: shipmentInclude }); return mapShipment(current); }
      const legal = (shipment.status.code === 'PENDING' && ['SHIPPED', 'CANCELLED'].includes(input.status)) || (shipment.status.code === 'SHIPPED' && input.status === 'DELIVERED'); if (!legal) throw new AppError(409, 'INVALID_STATE', 'Shipment status transition is not allowed.');
      const next = await tx.shipmentStatus.findUniqueOrThrow({ where: { code: input.status } });
      const movementCode = input.status === 'DELIVERED' ? 'SALE' : input.status === 'CANCELLED' ? 'RELEASE' : null;
      if (movementCode) { const movementType = await tx.inventoryMovementType.findUniqueOrThrow({ where: { code: movementCode } }); for (const item of shipment.items) { if (!item.orderItem.productVariantId) continue; const inventory = await tx.inventory.findUnique({ where: { warehouseId_productVariantId: { warehouseId: shipment.warehouseId, productVariantId: item.orderItem.productVariantId } } }); if (!inventory) throw new AppError(422, 'INSUFFICIENT_INVENTORY', 'Inventory balance is missing for this shipment.'); const update = input.status === 'DELIVERED' ? { onHandQty: { decrement: item.quantity }, reservedQty: { decrement: item.quantity } } : { reservedQty: { decrement: item.quantity } }; const updated = await tx.inventory.updateMany({ where: { id: inventory.id, version: inventory.version, ...(input.status === 'DELIVERED' ? { onHandQty: { gte: item.quantity }, reservedQty: { gte: item.quantity } } : { reservedQty: { gte: item.quantity } }) }, data: { ...update, version: { increment: 1 } } }); if (updated.count !== 1) throw new AppError(409, 'INVENTORY_CONFLICT', 'Inventory changed; retry the status update.'); await tx.inventoryMovement.create({ data: { inventoryId: inventory.id, typeId: movementType.id, quantityDelta: input.status === 'DELIVERED' ? -item.quantity : 0, reservedDelta: -item.quantity, referenceKey: `shipment:${shipment.id}:${movementCode.toLowerCase()}:${item.orderItemId}`, referenceType: input.status === 'DELIVERED' ? 'SHIPMENT_DELIVERY' : 'SHIPMENT_RELEASE', referenceId: shipment.id } }); } }
      await tx.shipment.update({ where: { id: shipmentId }, data: { statusId: next.id, shippedAt: input.status === 'SHIPPED' ? new Date() : undefined, deliveredAt: input.status === 'DELIVERED' ? new Date() : undefined } }); await tx.shipmentStatusHistory.create({ data: { shipmentId, statusId: next.id, location: input.location, details: input.details } });
      if (input.status === 'DELIVERED') { const remaining = await tx.orderItem.findMany({ where: { orderId: shipment.orderId }, include: { shipmentItems: { where: { shipment: { status: { code: 'DELIVERED' } } } } } }); if (remaining.every((item) => item.shipmentItems.reduce((sum, row) => sum + row.quantity, 0) >= item.quantity)) { const completed = await tx.orderStatus.findUniqueOrThrow({ where: { code: 'COMPLETED' } }); await tx.order.update({ where: { id: shipment.orderId }, data: { statusId: completed.id } }); await tx.orderStatusHistory.create({ data: { orderId: shipment.orderId, fromStatusId: shipment.order.statusId, toStatusId: completed.id, reason: 'All order items delivered' } }); } }
      const result = await tx.shipment.findUniqueOrThrow({ where: { id: shipmentId }, include: shipmentInclude }); return mapShipment(result);
    });
  }
}
