import { Prisma, PrismaClient } from '@prisma/client';
import { AppError } from '../../../shared/domain/AppError.js';
import type { ReturnItemInput, ReturnRepository } from '../domain/ReturnsRepository.js';

const include = { status: true, reason: true, items: { include: { orderItem: true, condition: true, resolution: true } }, refunds: { include: { status: true } } } satisfies Prisma.ReturnRequestInclude;
function mapReturn(row: Prisma.ReturnRequestGetPayload<{ include: typeof include }>) { return { id: row.id, orderId: row.orderId, userId: row.userId, status: row.status.code, reason: row.reason.code, note: row.note, items: row.items.map((item) => ({ orderItemId: item.orderItemId, quantity: item.quantity, condition: item.condition?.code ?? null, resolution: item.resolution?.code ?? null })), refunds: row.refunds.map((refund) => ({ id: refund.id, status: refund.status.code, amountMinor: Number(refund.amountMinor), currency: refund.currency })), requestedAt: row.requestedAt.toISOString(), approvedAt: row.approvedAt?.toISOString() ?? null, receivedAt: row.receivedAt?.toISOString() ?? null }; }

export class PrismaReturnsRepository implements ReturnRepository {
  constructor(private readonly db: PrismaClient) {}
  async createReturn(userId: string, orderId: string, reasonCode: string, items: ReturnItemInput[], note?: string): Promise<unknown> { return this.db.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: orderId, userId }, include: { items: true } }); if (!order) throw new AppError(404, 'NOT_FOUND', 'Order not found.'); const reason = await tx.returnReason.findUnique({ where: { code: reasonCode.toUpperCase() } }); if (!reason) throw new AppError(400, 'INVALID_RETURN_REASON', 'Return reason is not supported.'); const seen = new Set<string>(); for (const input of items) { if (seen.has(input.orderItemId)) throw new AppError(400, 'DUPLICATE_RESOURCE', 'Each order item may appear once per return.'); seen.add(input.orderItemId); const item = order.items.find((candidate) => candidate.id === input.orderItemId); if (!item) throw new AppError(400, 'INVALID_RETURN_ITEM', 'Return item does not belong to this order.'); const delivered = await tx.shipmentItem.aggregate({ where: { orderItemId: item.id, shipment: { status: { code: 'DELIVERED' } } }, _sum: { quantity: true } }); const returned = await tx.returnItem.aggregate({ where: { orderItemId: item.id, returnRequest: { status: { code: { notIn: ['REJECTED'] } } } }, _sum: { quantity: true } }); if ((delivered._sum.quantity ?? 0) - (returned._sum.quantity ?? 0) < input.quantity) throw new AppError(422, 'RETURN_INELIGIBLE', 'Requested quantity is not eligible for return.'); } const status = await tx.returnStatus.findUniqueOrThrow({ where: { code: 'REQUESTED' } }); const created = await tx.returnRequest.create({ data: { orderId, userId, statusId: status.id, reasonId: reason.id, note, items: { create: items } }, include }); return mapReturn(created); }); }
  async listReturns(userId: string): Promise<unknown[]> { const rows = await this.db.returnRequest.findMany({ where: { userId }, include, orderBy: { requestedAt: 'desc' } }); return rows.map(mapReturn); }
  async findReturn(userId: string, returnId: string): Promise<unknown | null> { const row = await this.db.returnRequest.findFirst({ where: { id: returnId, userId }, include }); return row ? mapReturn(row) : null; }
  async adminListReturns(): Promise<unknown[]> { const rows = await this.db.returnRequest.findMany({ include, orderBy: { requestedAt: 'asc' } }); return rows.map(mapReturn); }
  async adminUpdateReturn(returnId: string, nextCode: 'APPROVED' | 'RECEIVED' | 'REJECTED' | 'CLOSED', resolutionCode?: string, note?: string): Promise<unknown> { return this.db.$transaction(async (tx) => { const row = await tx.returnRequest.findUnique({ where: { id: returnId }, include: { status: true } }); if (!row) throw new AppError(404, 'NOT_FOUND', 'Return request not found.'); const legal = (row.status.code === 'REQUESTED' && ['APPROVED', 'REJECTED'].includes(nextCode)) || (row.status.code === 'APPROVED' && nextCode === 'RECEIVED') || (row.status.code === 'RECEIVED' && nextCode === 'CLOSED'); if (!legal) throw new AppError(409, 'INVALID_STATE', 'Return status transition is not allowed.'); const status = await tx.returnStatus.findUniqueOrThrow({ where: { code: nextCode } }); const resolution = resolutionCode ? await tx.returnResolution.findUnique({ where: { code: resolutionCode.toUpperCase() } }) : null; if (resolutionCode && !resolution) throw new AppError(400, 'INVALID_RESOLUTION', 'Return resolution is not supported.'); const updated = await tx.returnRequest.update({ where: { id: returnId }, data: { statusId: status.id, note: note ?? undefined, approvedAt: nextCode === 'APPROVED' ? new Date() : undefined, receivedAt: nextCode === 'RECEIVED' ? new Date() : undefined, items: resolution ? { updateMany: { where: {}, data: { resolutionId: resolution.id } } } : undefined }, include }); return mapReturn(updated); }); }
  async createRefund(returnId: string, idempotencyKey: string): Promise<unknown> { return this.db.$transaction(async (tx) => { const existing = await tx.refund.findFirst({ where: { returnRequestId: returnId, idempotencyKey }, include: { status: true } }); if (existing) return { id: existing.id, status: existing.status.code, amountMinor: Number(existing.amountMinor), currency: existing.currency }; const request = await tx.returnRequest.findUnique({ where: { id: returnId }, include: { status: true, order: { include: { payments: { include: { status: true }, orderBy: { createdAt: 'desc' } } } }, items: { include: { orderItem: true } } } }); if (!request) throw new AppError(404, 'NOT_FOUND', 'Return request not found.'); if (request.status.code !== 'RECEIVED') throw new AppError(409, 'INVALID_STATE', 'Return must be received before refund creation.'); const payment = request.order.payments.find((candidate) => candidate.status.code === 'PAID'); if (!payment) throw new AppError(422, 'PAYMENT_NOT_SETTLED', 'A settled payment is required for a refund.'); const amount = request.items.reduce((sum, item) => sum + BigInt(item.quantity) * item.orderItem.unitPriceMinor, 0n); const refunded = await tx.refund.aggregate({ where: { paymentId: payment.id, status: { code: { in: ['REQUESTED', 'PROCESSING', 'SUCCEEDED'] } } }, _sum: { amountMinor: true } }); if (amount <= 0n || amount + (refunded._sum.amountMinor ?? 0n) > payment.amountMinor) throw new AppError(422, 'REFUND_INELIGIBLE', 'Refund exceeds the remaining refundable payment amount.'); const status = await tx.refundStatus.findUniqueOrThrow({ where: { code: 'REQUESTED' } }); const refund = await tx.refund.create({ data: { paymentId: payment.id, returnRequestId: returnId, statusId: status.id, idempotencyKey, amountMinor: amount, currency: payment.currency, reason: 'Approved returned items' }, include: { status: true } }); return { id: refund.id, status: refund.status.code, amountMinor: Number(refund.amountMinor), currency: refund.currency }; }); }
}
