import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { afterAll, describe, expect, it } from 'vitest';
import { PrismaCheckoutRepository } from '../src/modules/checkout/infrastructure/PrismaCheckoutRepository.js';

const databaseUrl = process.env.CHECKOUT_INTEGRATION_DATABASE_URL;
const db = databaseUrl ? new PrismaClient({ datasources: { db: { url: databaseUrl } } }) : undefined;
const suite = describe.skipIf(!db);

suite('PrismaCheckoutRepository shipping selections', () => {
  afterAll(async () => { await db?.$disconnect(); });
  it('quotes and snapshots one authoritative rate per store, then rejects a stale disabled rate without mutating the cart', async () => {
    const suffix = randomUUID(); const activeUser = await db!.userStatus.upsert({ where: { code: 'ACTIVE' }, create: { code: 'ACTIVE' }, update: {} }); const activeStore = await db!.storeStatus.upsert({ where: { code: 'ACTIVE' }, create: { code: 'ACTIVE' }, update: {} }); const activeProduct = await db!.productStatus.upsert({ where: { code: 'ACTIVE' }, create: { code: 'ACTIVE' }, update: {} }); const pending = await db!.orderStatus.upsert({ where: { code: 'PENDING_PAYMENT' }, create: { code: 'PENDING_PAYMENT' }, update: {} }); await db!.orderAddressType.upsert({ where: { code: 'SHIPPING' }, create: { code: 'SHIPPING' }, update: {} }); await db!.orderAddressType.upsert({ where: { code: 'BILLING' }, create: { code: 'BILLING' }, update: {} });
    const country = await db!.country.create({ data: { iso2: `T${suffix.slice(0, 1)}`, name: `Country ${suffix}`, phoneCode: '+999' } }); const state = await db!.stateProvince.create({ data: { countryId: country.id, code: suffix.slice(0, 8), name: `State ${suffix}` } }); const city = await db!.city.create({ data: { stateProvinceId: state.id, name: `City ${suffix}` } }); const customer = await db!.user.create({ data: { email: `buyer-${suffix}@example.test`, firstName: 'Buyer', lastName: 'Test', statusId: activeUser.id } }); const sellerUser = await db!.user.create({ data: { email: `seller-${suffix}@example.test`, firstName: 'Seller', lastName: 'Test', statusId: activeUser.id } }); const verification = await db!.sellerVerificationStatus.create({ data: { code: `VERIFIED_${suffix}` } }); const seller = await db!.sellerProfile.create({ data: { userId: sellerUser.id, legalName: 'Test Seller', verificationStatusId: verification.id } }); const store = await db!.store.create({ data: { sellerProfileId: seller.id, slug: `store-${suffix}`, displayName: 'Test Store', statusId: activeStore.id } }); const product = await db!.product.create({ data: { storeId: store.id, name: 'Test Product', slug: `product-${suffix}`, description: 'Test', statusId: activeProduct.id } }); const variant = await db!.productVariant.create({ data: { productId: product.id, sku: `SKU-${suffix}` } }); await db!.productVariantPrice.create({ data: { productVariantId: variant.id, amountMinor: 1000n, currency: 'NGN' } }); const address = await db!.address.create({ data: { userId: customer.id, recipientName: 'Buyer', phoneE164: '+2348012345678', line1: '1 Test Road', cityId: city.id } }); const carrier = await db!.shippingCarrier.create({ data: { name: `Carrier ${suffix}` } }); const method = await db!.shippingMethod.create({ data: { carrierId: carrier.id, code: 'STANDARD', name: 'Standard', serviceLevel: 'Configured service' } }); const rate = await db!.shippingRate.create({ data: { storeId: store.id, shippingMethodId: method.id, cityId: city.id, amountMinor: 250n, currency: 'NGN' } }); await db!.cart.create({ data: { userId: customer.id, currency: 'NGN', items: { create: { productVariantId: variant.id, quantity: 2, unitPriceMinor: 1000n, currency: 'NGN' } } } });
    try { const repository = new PrismaCheckoutRepository(db!); const options = await repository.shippingOptions(customer.id, address.id) as { groups: Array<{ options: Array<{ id: string }> }> }; expect(options.groups[0]?.options[0]?.id).toBe(rate.id); const input = { shippingAddressId: address.id, shippingSelections: [{ storeId: store.id, shippingRateId: rate.id }] }; const quote = await repository.quote(customer.id, input) as { shippingMinor: number; totalMinor: number }; expect(quote).toMatchObject({ shippingMinor: 250, totalMinor: 2250 }); const order = await repository.placeOrder(customer.id, { ...input, idempotencyKey: `key-${suffix}` }) as { id: string; totals: { shippingMinor: number; totalMinor: number }; shippingSelections: unknown[] }; expect(order.totals).toMatchObject({ shippingMinor: 250, totalMinor: 2250 }); expect(order.shippingSelections).toHaveLength(1); expect((await db!.cart.findUnique({ where: { userId: customer.id }, include: { items: true } }))?.items).toHaveLength(0); await db!.shippingRate.update({ where: { id: rate.id }, data: { isActive: false } }); await db!.cartItem.create({ data: { cartId: (await db!.cart.findUniqueOrThrow({ where: { userId: customer.id } })).id, productVariantId: variant.id, quantity: 1, unitPriceMinor: 1000n, currency: 'NGN' } }); await expect(repository.quote(customer.id, input)).rejects.toMatchObject({ code: 'INVALID_SHIPPING_SELECTION' }); expect((await db!.cart.findUniqueOrThrow({ where: { userId: customer.id }, include: { items: true } })).items).toHaveLength(1); await db!.order.delete({ where: { id: order.id } }); } finally { await db!.cart.deleteMany({ where: { userId: customer.id } }); await db!.shippingRate.delete({ where: { id: rate.id } }); await db!.shippingMethod.delete({ where: { id: method.id } }); await db!.shippingCarrier.delete({ where: { id: carrier.id } }); await db!.address.delete({ where: { id: address.id } }); await db!.product.delete({ where: { id: product.id } }); await db!.store.delete({ where: { id: store.id } }); await db!.sellerProfile.delete({ where: { id: seller.id } }); await db!.user.deleteMany({ where: { id: { in: [customer.id, sellerUser.id] } } }); await db!.sellerVerificationStatus.delete({ where: { id: verification.id } }); await db!.city.delete({ where: { id: city.id } }); await db!.stateProvince.delete({ where: { id: state.id } }); await db!.country.delete({ where: { id: country.id } }); }
  });
});
