import { Prisma, PrismaClient } from '@prisma/client';
import { AppError } from '../../../shared/domain/AppError.js';
import type { AdminRepository } from '../domain/AdminRepository.js';
export class PrismaAdminRepository implements AdminRepository {
  constructor(private readonly db: PrismaClient) {}
  async listCategories() { return this.db.category.findMany({ include: { parent: true }, orderBy: [{ parentCategoryId: 'asc' }, { name: 'asc' }] }); }
  async getCategory(id: string) { return this.db.category.findUnique({ where: { id }, include: { parent: true, children: true } }); }
  async createCategory(actorId: string, input: { name: string; slug: string; parentCategoryId?: string | null }) {
    try {
      return await this.db.$transaction(async (tx) => {
        if (input.parentCategoryId && !await tx.category.findUnique({ where: { id: input.parentCategoryId }, select: { id: true } })) throw new AppError(400, 'INVALID_PARENT_CATEGORY', 'Parent category not found.');
        const created = await tx.category.create({ data: { name: input.name, slug: input.slug, parentCategoryId: input.parentCategoryId ?? null } });
        await tx.auditLog.create({ data: { actorUserId: actorId, action: 'CATEGORY_CREATED', entityType: 'Category', entityId: created.id, beforeData: Prisma.JsonNull, afterData: { name: created.name, slug: created.slug, parentCategoryId: created.parentCategoryId } } });
        return created;
      });
    } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Category slug is already in use.'); throw error; }
  }
  async updateCategory(actorId: string, id: string, input: { name?: string; slug?: string; parentCategoryId?: string | null; isActive?: boolean }) {
    try {
      return await this.db.$transaction(async (tx) => {
        const current = await tx.category.findUnique({ where: { id }, select: { id: true, name: true, slug: true, parentCategoryId: true, isActive: true } }); if (!current) throw new AppError(404, 'NOT_FOUND', 'Category not found.');
        if (input.parentCategoryId) { if (input.parentCategoryId === id) throw new AppError(400, 'INVALID_PARENT_CATEGORY', 'A category cannot be its own parent.'); let cursor: string | null = input.parentCategoryId; while (cursor) { if (cursor === id) throw new AppError(400, 'CATEGORY_CYCLE', 'Category hierarchy cannot contain a cycle.'); const parent: { parentCategoryId: string | null } | null = await tx.category.findUnique({ where: { id: cursor }, select: { parentCategoryId: true } }); if (!parent) throw new AppError(400, 'INVALID_PARENT_CATEGORY', 'Parent category not found.'); cursor = parent.parentCategoryId; } }
        const updated = await tx.category.update({ where: { id }, data: input });
        await tx.auditLog.create({ data: { actorUserId: actorId, action: 'CATEGORY_UPDATED', entityType: 'Category', entityId: id, beforeData: current, afterData: updated } });
        return updated;
      });
    } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Category slug is already in use.'); throw error; }
  }
  async listBrands() { return this.db.brand.findMany({ orderBy: { name: 'asc' } }); }
  async getBrand(id: string) { return this.db.brand.findUnique({ where: { id } }); }
  async createBrand(actorId: string, input: { name: string; slug: string; description?: string | null }) { try { return await this.db.$transaction(async (tx) => { const created = await tx.brand.create({ data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'BRAND_CREATED', entityType: 'Brand', entityId: created.id, beforeData: Prisma.JsonNull, afterData: { name: created.name, slug: created.slug } } }); return created; }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Brand name or slug is already in use.'); throw error; } }
  async updateBrand(actorId: string, id: string, input: { name?: string; slug?: string; description?: string | null }) { try { return await this.db.$transaction(async (tx) => { const current = await tx.brand.findUnique({ where: { id }, select: { id: true, name: true, slug: true, description: true } }); if (!current) throw new AppError(404, 'NOT_FOUND', 'Brand not found.'); const updated = await tx.brand.update({ where: { id }, data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'BRAND_UPDATED', entityType: 'Brand', entityId: id, beforeData: current, afterData: updated } }); return updated; }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Brand name or slug is already in use.'); throw error; } }
  async listUsers() { const rows = await this.db.user.findMany({ include: { status: true, roles: { include: { role: true } } }, orderBy: { createdAt: 'desc' }, take: 100 }); return rows.map((u) => ({ id: u.id, email: u.email, firstName: u.firstName, lastName: u.lastName, status: u.status.code, roles: u.roles.map((r) => r.role.code), createdAt: u.createdAt.toISOString() })); }
  async updateUserStatus(actorId: string, userId: string, status: string, reason: string) { return this.db.$transaction(async (tx) => { const user = await tx.user.findUnique({ where: { id: userId }, include: { status: true } }); if (!user) throw new AppError(404, 'NOT_FOUND', 'User not found.'); const next = await tx.userStatus.findUniqueOrThrow({ where: { code: status } }); await tx.user.update({ where: { id: userId }, data: { statusId: next.id } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'USER_STATUS_CHANGED', entityType: 'User', entityId: userId, beforeData: { status: user.status.code }, afterData: { status }, } }); return { id: userId, status }; }); }
  async replaceUserRoles(actorId: string, userId: string, roleCodes: string[]) { return this.db.$transaction(async (tx) => { const user = await tx.user.findUnique({ where: { id: userId }, include: { roles: { include: { role: true } } } }); if (!user) throw new AppError(404, 'NOT_FOUND', 'User not found.'); const roles = await tx.role.findMany({ where: { code: { in: roleCodes } } }); if (roles.length !== roleCodes.length) throw new AppError(400, 'INVALID_ROLE', 'One or more roles are invalid.'); await tx.userRole.deleteMany({ where: { userId } }); await tx.userRole.createMany({ data: roles.map((role) => ({ userId, roleId: role.id })) }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'USER_ROLES_REPLACED', entityType: 'User', entityId: userId, beforeData: { roles: user.roles.map((r) => r.role.code) }, afterData: { roles: roleCodes } } }); return { userId, roles: roleCodes }; }); }
  async listSellerApplications() { const rows = await this.db.sellerProfile.findMany({ include: { verificationStatus: true }, orderBy: { createdAt: 'asc' } }); return rows.map((r) => ({ id: r.id, userId: r.userId, legalName: r.legalName, businessRegistration: r.businessRegistration, verificationStatus: r.verificationStatus.code, createdAt: r.createdAt.toISOString() })); }
  async updateSellerApplication(actorId: string, sellerId: string, status: string, reason?: string) { return this.db.$transaction(async (tx) => { const profile = await tx.sellerProfile.findUnique({ where: { id: sellerId }, include: { verificationStatus: true } }); if (!profile) throw new AppError(404, 'NOT_FOUND', 'Seller application not found.'); const next = await tx.sellerVerificationStatus.findUniqueOrThrow({ where: { code: status } }); await tx.sellerProfile.update({ where: { id: sellerId }, data: { verificationStatusId: next.id } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SELLER_STATUS_CHANGED', entityType: 'SellerProfile', entityId: sellerId, beforeData: { status: profile.verificationStatus.code }, afterData: { status, reason } } }); return { id: sellerId, verificationStatus: status }; }); }
  async moderateProduct(actorId: string, productId: string, status: string, reason?: string) { return this.db.$transaction(async (tx) => { const product = await tx.product.findUnique({ where: { id: productId }, include: { status: true } }); if (!product) throw new AppError(404, 'NOT_FOUND', 'Product not found.'); const next = await tx.productStatus.findUniqueOrThrow({ where: { code: status } }); await tx.product.update({ where: { id: productId }, data: { statusId: next.id } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'PRODUCT_STATUS_CHANGED', entityType: 'Product', entityId: productId, beforeData: { status: product.status.code }, afterData: { status, reason } } }); return { id: productId, status }; }); }
  async listAuditLogs() { const rows = await this.db.auditLog.findMany({ orderBy: { occurredAt: 'desc' }, take: 200 }); return rows.map((r) => ({ id: r.id, actorUserId: r.actorUserId, action: r.action, entityType: r.entityType, entityId: r.entityId, beforeData: r.beforeData, afterData: r.afterData, occurredAt: r.occurredAt.toISOString() })); }
  async listShippingCarriers() { return this.db.shippingCarrier.findMany({ orderBy: { name: 'asc' } }); }
  async createShippingCarrier(actorId: string, input: { name: string; trackingUrlTemplate?: string | null; isActive?: boolean }) { try { return await this.db.$transaction(async (tx) => { const row = await tx.shippingCarrier.create({ data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_CARRIER_CREATED', entityType: 'ShippingCarrier', entityId: row.id, beforeData: Prisma.JsonNull, afterData: { name: row.name, isActive: row.isActive } } }); return row; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Carrier name is already in use.'); throw e; } }
  async updateShippingCarrier(actorId: string, id: string, input: { name?: string; trackingUrlTemplate?: string | null; isActive?: boolean }) { try { return await this.db.$transaction(async (tx) => { const before = await tx.shippingCarrier.findUnique({ where: { id } }); if (!before) throw new AppError(404, 'NOT_FOUND', 'Shipping carrier not found.'); const row = await tx.shippingCarrier.update({ where: { id }, data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_CARRIER_UPDATED', entityType: 'ShippingCarrier', entityId: id, beforeData: before, afterData: row } }); return row; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Carrier name is already in use.'); throw e; } }
  async listShippingMethods() { const rows = await this.db.shippingMethod.findMany({ include: { carrier: true }, orderBy: [{ carrier: { name: 'asc' } }, { name: 'asc' }] }); return rows.map((row) => ({ ...row, carrier: { id: row.carrier.id, name: row.carrier.name, isActive: row.carrier.isActive } })); }
  async createShippingMethod(actorId: string, input: { carrierId: string; code: string; name: string; serviceLevel: string; isActive?: boolean }) { try { return await this.db.$transaction(async (tx) => { if (!await tx.shippingCarrier.findUnique({ where: { id: input.carrierId }, select: { id: true } })) throw new AppError(404, 'NOT_FOUND', 'Shipping carrier not found.'); const row = await tx.shippingMethod.create({ data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_METHOD_CREATED', entityType: 'ShippingMethod', entityId: row.id, beforeData: Prisma.JsonNull, afterData: { carrierId: row.carrierId, code: row.code, name: row.name, isActive: row.isActive } } }); return row; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Carrier method code is already in use.'); throw e; } }
  async updateShippingMethod(actorId: string, id: string, input: { code?: string; name?: string; serviceLevel?: string; isActive?: boolean }) { try { return await this.db.$transaction(async (tx) => { const before = await tx.shippingMethod.findUnique({ where: { id } }); if (!before) throw new AppError(404, 'NOT_FOUND', 'Shipping method not found.'); const row = await tx.shippingMethod.update({ where: { id }, data: input }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_METHOD_UPDATED', entityType: 'ShippingMethod', entityId: id, beforeData: before, afterData: row } }); return row; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'Carrier method code is already in use.'); throw e; } }
  async listShippingRates() { const rows = await this.db.shippingRate.findMany({ include: { store: true, city: { include: { stateProvince: true } }, shippingMethod: { include: { carrier: true } } }, orderBy: { createdAt: 'desc' } }); return rows.map((row) => ({ id: row.id, store: { id: row.store.id, slug: row.store.slug, displayName: row.store.displayName }, city: { id: row.city.id, name: row.city.name, stateName: row.city.stateProvince.name }, shippingMethod: { id: row.shippingMethod.id, carrierName: row.shippingMethod.carrier.name, code: row.shippingMethod.code, name: row.shippingMethod.name }, amountMinor: Number(row.amountMinor), currency: row.currency, isActive: row.isActive })); }
  async createShippingRate(actorId: string, input: { storeId: string; shippingMethodId: string; cityId: string; amountMinor: number; currency: string; isActive?: boolean }) { try { return await this.db.$transaction(async (tx) => { const [store, method, city] = await Promise.all([tx.store.findUnique({ where: { id: input.storeId }, select: { id: true } }), tx.shippingMethod.findUnique({ where: { id: input.shippingMethodId }, select: { id: true } }), tx.city.findUnique({ where: { id: input.cityId }, select: { id: true } })]); if (!store || !method || !city) throw new AppError(404, 'NOT_FOUND', 'Store, shipping method, or destination city not found.'); const row = await tx.shippingRate.create({ data: { ...input, amountMinor: BigInt(input.amountMinor) } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_RATE_CREATED', entityType: 'ShippingRate', entityId: row.id, beforeData: Prisma.JsonNull, afterData: { storeId: row.storeId, shippingMethodId: row.shippingMethodId, cityId: row.cityId, amountMinor: row.amountMinor.toString(), currency: row.currency, isActive: row.isActive } } }); return { ...row, amountMinor: Number(row.amountMinor) }; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new AppError(409, 'DUPLICATE_RESOURCE', 'A rate already exists for this store, method, and city.'); throw e; } }
  async updateShippingRate(actorId: string, id: string, input: { amountMinor?: number; currency?: string; isActive?: boolean }) { return this.db.$transaction(async (tx) => { const before = await tx.shippingRate.findUnique({ where: { id } }); if (!before) throw new AppError(404, 'NOT_FOUND', 'Shipping rate not found.'); const row = await tx.shippingRate.update({ where: { id }, data: { ...input, ...(input.amountMinor === undefined ? {} : { amountMinor: BigInt(input.amountMinor) }) } }); await tx.auditLog.create({ data: { actorUserId: actorId, action: 'SHIPPING_RATE_UPDATED', entityType: 'ShippingRate', entityId: id, beforeData: { ...before, amountMinor: before.amountMinor.toString() }, afterData: { ...row, amountMinor: row.amountMinor.toString() } } }); return { ...row, amountMinor: Number(row.amountMinor) }; }); }
}
