import { Router, type NextFunction, type Request, type Response } from 'express';
import type { AuthService } from '../../identity/application/AuthService.js';
import { requireAuthentication, requirePermission } from '../../../shared/presentation/auth.js';
import { AppError } from '../../../shared/domain/AppError.js';
import type { NotificationService } from '../application/NotificationService.js';
const asyncRoute = (handler: (req: Request, res: Response) => Promise<void>) => (req: Request, res: Response, next: NextFunction): void => { void handler(req, res).catch(next); };
const param = (value: string | string[] | undefined): string => { if (typeof value !== 'string' || !value) throw new AppError(400, 'VALIDATION_ERROR', 'A route parameter is required.'); return value; };
export function createNotificationRouter(auth: AuthService, service: NotificationService): Router { const router = Router(); router.use(requireAuthentication(auth)); router.get('/me/notifications', asyncRoute(async (req, res) => { res.json({ data: await service.list(req.principal!.userId) }); })); router.patch('/me/notifications/:notificationId/read', asyncRoute(async (req, res) => { res.json({ data: await service.markRead(req.principal!.userId, param(req.params.notificationId)) }); })); return router; }
export function createAdminNotificationRouter(auth: AuthService, service: NotificationService): Router { const router = Router(); router.use(requireAuthentication(auth), requirePermission('notification:manage')); router.get('/notifications', asyncRoute(async (_req, res) => { res.json({ data: await service.listAdmin() }); })); router.post('/notifications/:notificationId/retry', asyncRoute(async (req, res) => { const key = req.header('idempotency-key'); if (!key || key.length < 16) throw new AppError(400, 'VALIDATION_ERROR', 'A valid Idempotency-Key header is required.'); res.status(202).json({ data: await service.retry(param(req.params.notificationId), key) }); })); return router; }
