import compression from 'compression';
import { randomUUID } from 'node:crypto';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import express, { type NextFunction, type Request, type Response } from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import { ZodError } from 'zod';
import { env } from './config/env.js';
import { AppError } from './shared/domain/AppError.js';
import { prisma } from './shared/infrastructure/prisma.js';
import { AuthService, ConsoleEmailSender } from './modules/identity/application/AuthService.js';
import { PrismaAuthRepository } from './modules/identity/infrastructure/PrismaAuthRepository.js';
import { createAuthRouter } from './modules/identity/presentation/auth.routes.js';
import { PrismaSellerRepository } from './modules/seller/infrastructure/PrismaSellerRepository.js';
import { SellerService } from './modules/seller/application/SellerService.js';
import { createPublicStoreRouter, createSellerRouter } from './modules/seller/presentation/seller.routes.js';
import { CatalogService } from './modules/catalog/application/CatalogService.js';
import { PrismaCatalogRepository } from './modules/catalog/infrastructure/PrismaCatalogRepository.js';
import { createCatalogRouter, createSellerProductRouter } from './modules/catalog/presentation/catalog.routes.js';
import { CartService } from './modules/cart/application/CartService.js';
import { PrismaCartRepository } from './modules/cart/infrastructure/PrismaCartRepository.js';
import { createCartRouter } from './modules/cart/presentation/cart.routes.js';
import { CheckoutService } from './modules/checkout/application/CheckoutService.js';
import { PrismaCheckoutRepository } from './modules/checkout/infrastructure/PrismaCheckoutRepository.js';
import { createAddressRouter, createCheckoutRouter, createLocationRouter } from './modules/checkout/presentation/checkout.routes.js';
import { PaymentService } from './modules/payments/application/PaymentService.js';
import { PrismaPaymentRepository } from './modules/payments/infrastructure/PrismaPaymentRepository.js';
import { PaystackHttpProvider } from './modules/payments/infrastructure/PaystackPaymentProvider.js';
import { createPaymentRouter, createPaymentWebhookRouter } from './modules/payments/presentation/payment.routes.js';
import { InventoryService } from './modules/inventory/application/InventoryService.js';
import { PrismaInventoryRepository } from './modules/inventory/infrastructure/PrismaInventoryRepository.js';
import { createInventoryRouter } from './modules/inventory/presentation/inventory.routes.js';
import { OrdersService } from './modules/orders/application/OrdersService.js';
import { PrismaOrdersRepository } from './modules/orders/infrastructure/PrismaOrdersRepository.js';
import { createOrdersRouter, createSellerOrdersRouter } from './modules/orders/presentation/orders.routes.js';
import { ReturnsService } from './modules/returns/application/ReturnsService.js';
import { PrismaReturnsRepository } from './modules/returns/infrastructure/PrismaReturnsRepository.js';
import { createAdminReturnsRouter, createReturnsRouter } from './modules/returns/presentation/returns.routes.js';
import { InvoiceService } from './modules/invoices/application/InvoiceService.js';
import { PrismaInvoiceRepository } from './modules/invoices/infrastructure/PrismaInvoiceRepository.js';
import { createAdminInvoiceRouter, createInvoiceRouter } from './modules/invoices/presentation/invoice.routes.js';
import { NotificationService } from './modules/notifications/application/NotificationService.js';
import { PrismaNotificationRepository } from './modules/notifications/infrastructure/PrismaNotificationRepository.js';
import { createAdminNotificationRouter, createNotificationRouter } from './modules/notifications/presentation/notification.routes.js';
import { AdminService } from './modules/admin/application/AdminService.js';
import { PrismaAdminRepository } from './modules/admin/infrastructure/PrismaAdminRepository.js';
import { createAdminRouter } from './modules/admin/presentation/admin.routes.js';
import { ReportsService } from './modules/reports/application/ReportsService.js';
import { PrismaReportsRepository } from './modules/reports/infrastructure/PrismaReportsRepository.js';
import { createReportsRouter } from './modules/reports/presentation/report.routes.js';
import { renderMetrics } from './shared/observability/metrics.js';
import { requestObservability } from './shared/presentation/observability.js';
import { requireAuthentication, requirePermission } from './shared/presentation/auth.js';
import { FixedWindowRateLimiter } from './shared/rate-limit/RateLimiter.js';
import { rateLimit } from './shared/presentation/rate-limit.js';

export function createApp(): express.Express {
  const app = express();
  const authService = new AuthService(new PrismaAuthRepository(prisma), new ConsoleEmailSender());
  const sellerService = new SellerService(new PrismaSellerRepository(prisma));
  const catalogService = new CatalogService(new PrismaCatalogRepository(prisma));
  const cartService = new CartService(new PrismaCartRepository(prisma));
  const checkoutService = new CheckoutService(new PrismaCheckoutRepository(prisma));
  const paymentService = new PaymentService(new PrismaPaymentRepository(prisma), env.PAYSTACK_SECRET_KEY ? new PaystackHttpProvider(env.PAYSTACK_SECRET_KEY, env.PAYSTACK_BASE_URL, env.PAYSTACK_TIMEOUT_MS) : undefined);
  const inventoryService = new InventoryService(new PrismaInventoryRepository(prisma));
  const ordersService = new OrdersService(new PrismaOrdersRepository(prisma));
  const returnsService = new ReturnsService(new PrismaReturnsRepository(prisma));
  const invoiceService = new InvoiceService(new PrismaInvoiceRepository(prisma));
  const notificationService = new NotificationService(new PrismaNotificationRepository(prisma));
  const adminService = new AdminService(new PrismaAdminRepository(prisma));
  const reportsService = new ReportsService(new PrismaReportsRepository(prisma));
  const localRateLimiter = new FixedWindowRateLimiter();
  app.disable('x-powered-by');
  app.use(helmet());
  app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
  app.use(compression());
  app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
  app.use(requestObservability);
  if (env.NODE_ENV !== 'production') app.use(rateLimit(localRateLimiter, { limit: env.RATE_LIMIT_MAX_REQUESTS, windowSeconds: env.RATE_LIMIT_WINDOW_SECONDS, scope: 'http' }));
  app.use(express.json({ limit: '100kb', verify: (req, _res, buffer) => { if ((req.url ?? '').startsWith('/api/v1/webhooks/')) (req as Request & { rawBody?: Buffer }).rawBody = Buffer.from(buffer); } }));
  app.use(cookieParser());
  app.get('/health/live', (_req, res) => res.json({ data: { status: 'ok' } }));
  app.get('/health/ready', async (_req, res, next) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ data: { status: 'ok' } }); } catch (error) { next(error); } });
  app.get('/metrics', requireAuthentication(authService), requirePermission('metrics:read'), (_req, res) => { res.type('text/plain').send(renderMetrics()); });
  app.use('/api/v1/auth', createAuthRouter(authService));
  app.use('/api/v1/seller', createSellerRouter(authService, sellerService));
  app.use('/api/v1/seller', createSellerProductRouter(authService, catalogService));
  app.use('/api/v1/stores', createPublicStoreRouter(sellerService));
  app.use('/api/v1', createCatalogRouter(catalogService));
  app.use('/api/v1/cart', createCartRouter(authService, cartService));
  app.use('/api/v1/me/addresses', createAddressRouter(authService, checkoutService));
  app.use('/api/v1/locations', createLocationRouter(checkoutService));
  app.use('/api/v1/checkout', createCheckoutRouter(authService, checkoutService));
  app.use('/api/v1/webhooks', createPaymentWebhookRouter(paymentService))
  app.use('/api/v1', createPaymentRouter(authService, paymentService));
  app.use('/api/v1/seller/inventory', createInventoryRouter(authService, inventoryService));
  app.use('/api/v1/orders', createOrdersRouter(authService, ordersService));
  app.use('/api/v1/seller', createSellerOrdersRouter(authService, ordersService));
  app.use('/api/v1', createReturnsRouter(authService, returnsService));
  app.use('/api/v1/admin', createAdminReturnsRouter(authService, returnsService));
  app.use('/api/v1', createInvoiceRouter(authService, invoiceService));
  app.use('/api/v1/admin', createAdminInvoiceRouter(authService, invoiceService));
  app.use('/api/v1', createNotificationRouter(authService, notificationService));
  app.use('/api/v1/admin', createAdminNotificationRouter(authService, notificationService));
  app.use('/api/v1/admin', createAdminRouter(authService, adminService));
  app.use('/api/v1/admin/reports', createReportsRouter(authService, reportsService));
  app.use((_req, _res, next) => next(new AppError(404, 'NOT_FOUND', 'Route not found.')));
  app.use((error: unknown, req: Request, res: Response, _next: NextFunction) => {
    const traceId = req.header('x-request-id') ?? randomUUID();
    if (error instanceof ZodError) return res.status(400).json({ type: 'https://api.arewaxpressmart.com/problems/validation-error', title: 'Request validation failed', status: 400, code: 'VALIDATION_ERROR', detail: 'One or more fields are invalid.', errors: error.issues.map((issue) => ({ field: issue.path.join('.'), message: issue.message })), traceId });
    if (error instanceof AppError) return res.status(error.status).json({ type: `https://api.arewaxpressmart.com/problems/${error.code.toLowerCase()}`, title: error.code, status: error.status, code: error.code, detail: error.message, traceId });
    console.error({ traceId, error });
    return res.status(500).json({ type: 'https://api.arewaxpressmart.com/problems/internal-error', title: 'Internal server error', status: 500, code: 'INTERNAL_ERROR', detail: 'An unexpected error occurred.', traceId });
  });
  return app;
}
