import { randomUUID } from 'node:crypto';
import { Prisma, PrismaClient } from '@prisma/client';
import { AppError } from '../../../shared/domain/AppError.js';
import type { AddressInput, CheckoutInput, CheckoutRepository } from '../domain/CheckoutRepository.js';

const addressInclude = { city: { include: { stateProvince: { include: { country: true } } } } } satisfies Prisma.AddressInclude;
const orderInclude = { status: true, addresses: { include: { type: true } }, items: { include: { store: true } }, shippingSelections: { include: { store: true } } } satisfies Prisma.OrderInclude;
type Tx = Prisma.TransactionClient;
function mapAddress(a: Prisma.AddressGetPayload<{ include: typeof addressInclude }>) { return { id: a.id, recipientName: a.recipientName, phoneE164: a.phoneE164, line1: a.line1, line2: a.line2, postalCode: a.postalCode, isDefaultShipping: a.isDefaultShipping, isDefaultBilling: a.isDefaultBilling, city: { id: a.city.id, name: a.city.name, state: { id: a.city.stateProvince.id, name: a.city.stateProvince.name, country: { code: a.city.stateProvince.country.iso2, name: a.city.stateProvince.country.name } } } }; }
function mapOrder(o: Prisma.OrderGetPayload<{ include: typeof orderInclude }>) { return { id: o.id, orderNumber: o.orderNumber, status: o.status.code, currency: o.currency, totals: { subtotalMinor: Number(o.subtotalMinor), discountMinor: Number(o.discountMinor), shippingMinor: Number(o.shippingMinor), taxMinor: Number(o.taxMinor), totalMinor: Number(o.totalMinor) }, addresses: o.addresses.map((a) => ({ type: a.type.code, recipientName: a.recipientName, phoneE164: a.phoneE164, line1: a.line1, line2: a.line2, cityName: a.cityName, stateName: a.stateName, countryCode: a.countryCode, postalCode: a.postalCode })), items: o.items.map((i) => ({ id: i.id, store: { id: i.store.id, slug: i.store.slug, displayName: i.store.displayName }, productName: i.productName, sku: i.sku, quantity: i.quantity, unitPriceMinor: Number(i.unitPriceMinor), lineTotalMinor: Number(i.lineTotalMinor), currency: i.currency })), shippingSelections: o.shippingSelections.map((s) => ({ id: s.id, store: { id: s.store.id, slug: s.store.slug, displayName: s.store.displayName }, shippingMethodId: s.shippingMethodId, carrierName: s.carrierName, methodCode: s.methodCode, methodName: s.methodName, serviceLevel: s.serviceLevel, amountMinor: Number(s.amountMinor), currency: s.currency })), placedAt: o.placedAt.toISOString() }; }

export class PrismaCheckoutRepository implements CheckoutRepository {
  constructor(private readonly db: PrismaClient) {}
  async listCountries(): Promise<unknown[]> { return this.db.country.findMany({ orderBy: { name: 'asc' }, select: { id: true, iso2: true, name: true } }); }
  async listStates(countryId?: string): Promise<unknown[]> { return this.db.stateProvince.findMany({ where: countryId ? { countryId } : undefined, orderBy: { name: 'asc' }, select: { id: true, countryId: true, code: true, name: true } }); }
  async listCities(stateProvinceId?: string): Promise<unknown[]> { return this.db.city.findMany({ where: stateProvinceId ? { stateProvinceId } : undefined, orderBy: { name: 'asc' }, select: { id: true, stateProvinceId: true, name: true } }); }
  async listAddresses(userId: string): Promise<unknown[]> { return (await this.db.address.findMany({ where: { userId }, include: addressInclude, orderBy: { createdAt: 'asc' } })).map(mapAddress); }
  async createAddress(userId: string, input: AddressInput): Promise<unknown> { return mapAddress(await this.writeAddress(userId, input)); }
  async findAddressOwner(addressId: string): Promise<{ userId: string } | null> { return this.db.address.findUnique({ where: { id: addressId }, select: { userId: true } }); }
  async updateAddress(addressId: string, input: Partial<AddressInput>): Promise<unknown> { const userId = (await this.db.address.findUniqueOrThrow({ where: { id: addressId }, select: { userId: true } })).userId; return mapAddress(await this.writeAddress(userId, input, addressId)); }
  async deleteAddress(addressId: string): Promise<void> { await this.db.address.delete({ where: { id: addressId } }); }
  async shippingOptions(userId: string, shippingAddressId: string): Promise<unknown> { return this.db.$transaction(async (tx) => { const base = await this.buildBase(tx, userId, shippingAddressId); const groups = await this.options(tx, base.storeIds, base.shippingAddress.city.id, base.currency); this.assertAvailable(base.storeIds, groups); return { currency: base.currency, shippingAddress: mapAddress(base.shippingAddress), groups: groups.map((g) => ({ store: g.store, options: g.options.map((o) => ({ ...o, amountMinor: Number(o.amountMinor) })) })) }; }); }
  async quote(userId: string, input: CheckoutInput): Promise<unknown> { return this.mapQuote(await this.db.$transaction((tx) => this.buildQuote(tx, userId, input))); }
  async findOrderByIdempotencyKey(userId: string, key: string): Promise<unknown | null> { const order = await this.db.order.findUnique({ where: { userId_idempotencyKey: { userId, idempotencyKey: key } }, include: orderInclude }); return order ? mapOrder(order) : null; }
  async placeOrder(userId: string, input: CheckoutInput & { idempotencyKey: string }): Promise<unknown> { try { return await this.db.$transaction(async (tx) => { const q = await this.buildQuote(tx, userId, input); const [status, shippingType, billingType] = await Promise.all([tx.orderStatus.findUniqueOrThrow({ where: { code: 'PENDING_PAYMENT' }, select: { id: true } }), tx.orderAddressType.findUniqueOrThrow({ where: { code: 'SHIPPING' }, select: { id: true } }), tx.orderAddressType.findUniqueOrThrow({ where: { code: 'BILLING' }, select: { id: true } })]); const order = await tx.order.create({ data: { orderNumber: `AXM-${Date.now()}-${randomUUID().slice(0, 8).toUpperCase()}`, userId, statusId: status.id, idempotencyKey: input.idempotencyKey, currency: q.currency, subtotalMinor: q.subtotalMinor, shippingMinor: q.shippingMinor, totalMinor: q.totalMinor, addresses: { create: [this.snapshotAddress(shippingType.id, q.shippingAddress), this.snapshotAddress(billingType.id, q.billingAddress)] }, items: { create: q.lines.map((l) => ({ storeId: l.storeId, productVariantId: l.productVariantId, productName: l.productName, sku: l.sku, quantity: l.quantity, unitPriceMinor: l.unitPriceMinor, lineTotalMinor: l.lineTotalMinor, currency: l.currency })) }, shippingSelections: { create: q.selections.map((s) => ({ storeId: s.storeId, shippingMethodId: s.shippingMethodId, carrierName: s.carrierName, methodCode: s.methodCode, methodName: s.methodName, serviceLevel: s.serviceLevel, amountMinor: s.amountMinor, currency: s.currency })) } }, include: orderInclude }); await tx.cartItem.deleteMany({ where: { cartId: q.cartId } }); return mapOrder(order); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') { const prior = await this.findOrderByIdempotencyKey(userId, input.idempotencyKey); if (prior) return prior; } if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2034') throw new AppError(409, 'CHECKOUT_CONFLICT', 'Checkout changed concurrently; request a new quote and retry.'); throw error; } }
  private async buildBase(tx: Tx, userId: string, shippingAddressId: string) { const cart = await tx.cart.findUnique({ where: { userId }, include: { items: { include: { productVariant: { include: { product: { include: { store: { include: { status: true } }, status: true } }, prices: { where: { endsAt: null }, orderBy: { startsAt: 'desc' }, take: 1 } } } } } } }); if (!cart || !cart.items.length) throw new AppError(422, 'EMPTY_CART', 'Your cart is empty.'); const shippingAddress = await tx.address.findFirst({ where: { id: shippingAddressId, userId }, include: addressInclude }); if (!shippingAddress) throw new AppError(404, 'NOT_FOUND', 'Shipping address not found.'); const lines = cart.items.map((item) => { const variant = item.productVariant; const price = variant.prices[0]; if (!variant.isActive || variant.product.status.code !== 'ACTIVE' || variant.product.store.status.code !== 'ACTIVE') throw new AppError(422, 'PRODUCT_UNAVAILABLE', 'One or more cart items are no longer available.'); if (!price) throw new AppError(422, 'PRICE_UNAVAILABLE', 'One or more cart items have no active price.'); if (price.currency !== cart.currency) throw new AppError(422, 'CURRENCY_MISMATCH', 'All cart items must use the cart currency.'); return { productVariantId: variant.id, storeId: variant.product.store.id, productName: variant.product.name, sku: variant.sku, quantity: item.quantity, unitPriceMinor: price.amountMinor, lineTotalMinor: price.amountMinor * BigInt(item.quantity), currency: price.currency }; }); return { cartId: cart.id, currency: cart.currency, lines, storeIds: [...new Set(lines.map((l) => l.storeId))], shippingAddress }; }
  private async options(tx: Tx, storeIds: string[], cityId: string, currency: string) { const rows = await tx.shippingRate.findMany({ where: { storeId: { in: storeIds }, cityId, currency, isActive: true, shippingMethod: { isActive: true, carrier: { isActive: true } } }, include: { store: true, shippingMethod: { include: { carrier: true } } }, orderBy: [{ storeId: 'asc' }, { amountMinor: 'asc' }] }); const groups = new Map<string, { store: { id: string; slug: string; displayName: string }; options: Array<{ id: string; shippingMethodId: string; carrierName: string; methodCode: string; methodName: string; serviceLevel: string; amountMinor: bigint; currency: string }> }>(); for (const r of rows) { const g = groups.get(r.storeId) ?? { store: { id: r.store.id, slug: r.store.slug, displayName: r.store.displayName }, options: [] }; g.options.push({ id: r.id, shippingMethodId: r.shippingMethodId, carrierName: r.shippingMethod.carrier.name, methodCode: r.shippingMethod.code, methodName: r.shippingMethod.name, serviceLevel: r.shippingMethod.serviceLevel, amountMinor: r.amountMinor, currency: r.currency }); groups.set(r.storeId, g); } return [...groups.values()]; }
  private assertAvailable(storeIds: string[], groups: Array<{ store: { id: string } }>) { if (groups.length !== storeIds.length) throw new AppError(422, 'SHIPPING_UNAVAILABLE', 'Shipping is not available for one or more stores at this destination.'); }
  private async buildQuote(tx: Tx, userId: string, input: CheckoutInput) { const base = await this.buildBase(tx, userId, input.shippingAddressId); const billingAddress = input.billingAddressId ? await tx.address.findFirst({ where: { id: input.billingAddressId, userId }, include: addressInclude }) : base.shippingAddress; if (!billingAddress) throw new AppError(404, 'NOT_FOUND', 'Billing address not found.'); const stores = new Set(base.storeIds); if (input.shippingSelections.length !== stores.size) throw new AppError(422, 'SHIPPING_SELECTION_REQUIRED', 'Select exactly one shipping option for every store.'); const byRate = new Map<string, { storeId: string }>(); for (const s of input.shippingSelections) { if (!stores.has(s.storeId) || byRate.has(s.shippingRateId) || [...byRate.values()].some((v) => v.storeId === s.storeId)) throw new AppError(422, 'INVALID_SHIPPING_SELECTION', 'Shipping selections must match each cart store exactly once.'); byRate.set(s.shippingRateId, s); } const rates = await tx.shippingRate.findMany({ where: { id: { in: [...byRate.keys()] } }, include: { shippingMethod: { include: { carrier: true } } } }); if (rates.length !== byRate.size) throw new AppError(422, 'INVALID_SHIPPING_SELECTION', 'One or more shipping options are invalid.'); const selections = rates.map((r) => { const s = byRate.get(r.id)!; if (r.storeId !== s.storeId || r.cityId !== base.shippingAddress.city.id || !r.isActive || !r.shippingMethod.isActive || !r.shippingMethod.carrier.isActive) throw new AppError(422, 'INVALID_SHIPPING_SELECTION', 'One or more shipping options are not available for this destination.'); if (r.currency !== base.currency) throw new AppError(422, 'SHIPPING_CURRENCY_MISMATCH', 'A shipping option currency does not match the cart currency.'); return { storeId: r.storeId, shippingMethodId: r.shippingMethodId, carrierName: r.shippingMethod.carrier.name, methodCode: r.shippingMethod.code, methodName: r.shippingMethod.name, serviceLevel: r.shippingMethod.serviceLevel, amountMinor: r.amountMinor, currency: r.currency }; }); const subtotalMinor = base.lines.reduce((n, l) => n + l.lineTotalMinor, 0n); const shippingMinor = selections.reduce((n, s) => n + s.amountMinor, 0n); return { ...base, billingAddress, selections, subtotalMinor, shippingMinor, totalMinor: subtotalMinor + shippingMinor }; }
  private mapQuote(q: Awaited<ReturnType<PrismaCheckoutRepository['buildQuote']>>) { return { currency: q.currency, lines: q.lines.map((l) => ({ ...l, unitPriceMinor: Number(l.unitPriceMinor), lineTotalMinor: Number(l.lineTotalMinor) })), shippingSelections: q.selections.map((s) => ({ ...s, amountMinor: Number(s.amountMinor) })), subtotalMinor: Number(q.subtotalMinor), discountMinor: 0, shippingMinor: Number(q.shippingMinor), taxMinor: 0, totalMinor: Number(q.totalMinor), shippingAddress: mapAddress(q.shippingAddress), billingAddress: mapAddress(q.billingAddress) }; }
  private async writeAddress(userId: string, input: Partial<AddressInput>, addressId?: string) { return this.db.$transaction(async (tx) => { if (input.cityId && !await tx.city.findUnique({ where: { id: input.cityId }, select: { id: true } })) throw new AppError(404, 'NOT_FOUND', 'City not found.'); if (input.isDefaultShipping) await tx.address.updateMany({ where: { userId, ...(addressId ? { id: { not: addressId } } : {}) }, data: { isDefaultShipping: false } }); if (input.isDefaultBilling) await tx.address.updateMany({ where: { userId, ...(addressId ? { id: { not: addressId } } : {}) }, data: { isDefaultBilling: false } }); return addressId ? tx.address.update({ where: { id: addressId }, data: input, include: addressInclude }) : tx.address.create({ data: { userId, recipientName: input.recipientName!, phoneE164: input.phoneE164!, line1: input.line1!, line2: input.line2, cityId: input.cityId!, postalCode: input.postalCode, isDefaultShipping: input.isDefaultShipping, isDefaultBilling: input.isDefaultBilling }, include: addressInclude }); }); }
  private snapshotAddress(typeId: string, a: Prisma.AddressGetPayload<{ include: typeof addressInclude }>) { return { typeId, recipientName: a.recipientName, phoneE164: a.phoneE164, line1: a.line1, line2: a.line2, cityName: a.city.name, stateName: a.city.stateProvince.name, countryCode: a.city.stateProvince.country.iso2, postalCode: a.postalCode }; }
}
