import { useEffect, useState, type FormEvent } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { api, type Address, type AddressInput, type City, type Country, type Quote, type StateProvince } from './api';
import { useAuth } from './auth'; import { formatMoney } from './money';
import { PayNow } from './Payment';
import './checkout.css';
import './checkout.css';
const emptyForm: AddressInput = { recipientName: '', phoneE164: '', line1: '', line2: '', cityId: '', postalCode: '', isDefaultShipping: false, isDefaultBilling: false };
function PageState({ message, error }: { message?: string; error?: string | null }) { return <>{message && <p role="status" className="success">{message}</p>}{error && <p role="alert" className="error-text">{error}</p>}</>; }
export function Addresses() { const { user } = useAuth(); const [addresses, setAddresses] = useState<Address[]>([]); const [form, setForm] = useState<AddressInput>(emptyForm); const [countries, setCountries] = useState<Country[]>([]); const [states, setStates] = useState<StateProvince[]>([]); const [cities, setCities] = useState<City[]>([]); const [countryId, setCountryId] = useState(''); const [stateId, setStateId] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState(''); if (!user) return <Navigate to="/login" replace />;
  useEffect(() => { void Promise.all([api.addresses(), api.countries()]).then(([items, cs]) => { setAddresses(items); setCountries(cs); }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const submit = (e: FormEvent) => { e.preventDefault(); setError(null); setMessage(''); if (!form.recipientName || !form.phoneE164 || !form.line1 || !form.cityId) { setError('Recipient, phone, address line, and city are required.'); return; } void api.createAddress(form).then((address) => { setAddresses((current) => [...current, address]); setForm(emptyForm); setStateId(''); setMessage('Address saved.'); }).catch((e: Error) => setError(e.message)); };
  return <section className="page"><p className="eyebrow">DELIVERY</p><h1>Your addresses</h1><PageState error={error} message={message} /><div className="address-grid"><div><h2>Saved addresses</h2><Feedback loading={loading} empty={!loading && addresses.length === 0 ? 'No saved addresses yet.' : undefined} />{addresses.map((a) => <button className={`address-card ${a.isDefaultShipping ? 'selected' : ''}`} key={a.id} onClick={() => setForm((current) => ({ ...current, cityId: a.city.id, recipientName: a.recipientName, phoneE164: a.phoneE164, line1: a.line1, line2: a.line2, postalCode: a.postalCode }))}><strong>{a.recipientName}</strong><span>{a.line1}, {a.city.name}, {a.city.state.name}</span>{a.isDefaultShipping && <small>Default delivery address</small>}</button>)}</div><form className="stack" onSubmit={submit}><h2>Add an address</h2><label>Recipient name<input value={form.recipientName} onChange={(e) => setForm({ ...form, recipientName: e.target.value })} required /></label><label>Phone (E.164)<input value={form.phoneE164} onChange={(e) => setForm({ ...form, phoneE164: e.target.value })} placeholder="+2348012345678" required /></label><label>Address line<input value={form.line1} onChange={(e) => setForm({ ...form, line1: e.target.value })} required /></label><label>Additional line<input value={form.line2 ?? ''} onChange={(e) => setForm({ ...form, line2: e.target.value })} /></label><label>Country<select value={countryId} onChange={(e) => { setCountryId(e.target.value); setStateId(''); setForm({ ...form, cityId: '' }); void api.states(e.target.value).then(setStates).catch((err: Error) => setError(err.message)); }} required><option value="">Select country</option>{countries.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>State<select value={stateId} onChange={(e) => { setStateId(e.target.value); setForm({ ...form, cityId: '' }); void api.cities(e.target.value).then(setCities).catch((err: Error) => setError(err.message)); }} disabled={!countryId} required><option value="">Select state</option>{states.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>City<select value={form.cityId} onChange={(e) => setForm({ ...form, cityId: e.target.value })} disabled={!stateId} required><option value="">Select city</option>{cities.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Postal code<input value={form.postalCode ?? ''} onChange={(e) => setForm({ ...form, postalCode: e.target.value })} /></label><label className="checkbox"><input type="checkbox" checked={form.isDefaultShipping} onChange={(e) => setForm({ ...form, isDefaultShipping: e.target.checked })} /> Use as default shipping address</label><button className="button">Save address</button></form></div></section> }
function Feedback({ loading, empty }: { loading: boolean; empty?: string }) { if (loading) return <p role="status">Loading…</p>; return empty ? <p>{empty}</p> : null; }
export function Checkout() { const { user } = useAuth(); const navigate = useNavigate(); const [addresses, setAddresses] = useState<Address[]>([]); const [shippingAddressId, setShippingAddressId] = useState(''); const [billingAddressId, setBillingAddressId] = useState(''); const [quote, setQuote] = useState<Quote | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null); const [createdOrder, setCreatedOrder] = useState<Awaited<ReturnType<typeof api.placeOrder>> | null>(null); const [attemptKey, setAttemptKey] = useState<string | null>(null); if (!user) return <Navigate to="/login" replace />; useEffect(() => { void api.addresses().then((items) => { setAddresses(items); const preferred = items.find((item) => item.isDefaultShipping) ?? items[0]; if (preferred) setShippingAddressId(preferred.id); }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const key = () => attemptKey ?? (() => { const value = globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`; setAttemptKey(value); return value; })();
  const requestQuote = () => { if (!shippingAddressId) { setError('Select a delivery address first.'); return; } setError(null); setQuote(null); setWorking(true); void api.quote({ shippingAddressId, ...(billingAddressId ? { billingAddressId } : {}) }).then(setQuote).catch((e: Error) => setError(e.message)).finally(() => setWorking(false)); };
  const placeOrder = () => { if (!quote || !shippingAddressId) return; setError(null); setWorking(true); void api.placeOrder({ shippingAddressId, ...(billingAddressId ? { billingAddressId } : {}) }, key()).then(setCreatedOrder).catch((e: Error) => setError(e.message)).finally(() => setWorking(false)); };
  if (createdOrder) return <section className="narrow page"><p className="eyebrow">ORDER CREATED</p><h1>Thank you for your order</h1><p>Your order <strong>{createdOrder.orderNumber}</strong> is currently <strong>{createdOrder.status}</strong>.</p><p>Payment status: <strong>{createdOrder.paymentStatus ?? 'PENDING'}</strong>. Payment is not marked successful by this page.</p><PayNow order={createdOrder} /><Link className="button" to={`/orders/${createdOrder.id}`}>View order</Link> <Link className="button" to="/products">Continue shopping</Link></section>;
  return <section className="page"><p className="eyebrow">CHECKOUT</p><h1>Review your order</h1><PageState error={error} /><div className="checkout-grid"><div className="stack"><label>Delivery address<select value={shippingAddressId} onChange={(e) => { setShippingAddressId(e.target.value); setQuote(null); setAttemptKey(null); }} disabled={loading} required><option value="">Select an address</option>{addresses.map((a) => <option key={a.id} value={a.id}>{a.recipientName} — {a.line1}, {a.city.name}</option>)}</select></label><label>Billing address (optional)<select value={billingAddressId} onChange={(e) => { setBillingAddressId(e.target.value); setQuote(null); setAttemptKey(null); }}><option value="">Same as delivery</option>{addresses.map((a) => <option key={a.id} value={a.id}>{a.recipientName} — {a.line1}</option>)}</select></label><button className="button" onClick={requestQuote} disabled={working || !shippingAddressId}>Get secure quote</button><Link className="text-link" to="/addresses">Manage addresses</Link></div><div className="quote" aria-live="polite"><h2>Authoritative quote</h2>{working && !quote && <p role="status">Checking current prices and availability…</p>}{quote ? <><div className="quote-lines">{quote.lines.map((line) => <div key={line.productVariantId}><span>{line.productName} × {line.quantity}</span><strong>{formatMoney(line.lineTotalMinor, line.currency)}</strong></div>)}</div><dl><div><dt>Subtotal</dt><dd>{formatMoney(quote.subtotalMinor, quote.currency)}</dd></div><div><dt>Shipping</dt><dd>{formatMoney(quote.shippingMinor, quote.currency)}</dd></div><div><dt>Total</dt><dd><strong>{formatMoney(quote.totalMinor, quote.currency)}</strong></dd></div></dl><button className="button" onClick={placeOrder} disabled={working}>Place order</button></> : <p>Select an address and request a quote.</p>}</div></div></section> }
