import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { Checkout } from './Checkout';

vi.mock('./auth', () => ({ useAuth: () => ({ user: { id: 'u1' }, loading: false }) }));
vi.mock('./api', async () => { const actual = await vi.importActual<typeof import('./api')>('./api'); return { ...actual, api: { ...actual.api, addresses: vi.fn(), shippingOptions: vi.fn(), quote: vi.fn(), placeOrder: vi.fn() } }; });
import { api } from './api';

const address = { id: 'a1', recipientName: 'Amina', phoneE164: '+2348012345678', line1: '1 Market Road', line2: null, postalCode: null, isDefaultShipping: true, isDefaultBilling: false, city: { id: 'city', name: 'Kano', state: { id: 'state', name: 'Kano', country: { code: 'NG', name: 'Nigeria' } } } };
const options = { currency: 'NGN', shippingAddress: address, groups: [{ store: { id: 'store-a', slug: 'a', displayName: 'Store A' }, options: [{ id: 'rate-a', shippingMethodId: 'method-a', carrierName: 'Local', methodCode: 'STANDARD', methodName: 'Standard', serviceLevel: 'Configured service', amountMinor: 100, currency: 'NGN' }] }, { store: { id: 'store-b', slug: 'b', displayName: 'Store B' }, options: [{ id: 'rate-b', shippingMethodId: 'method-b', carrierName: 'Local', methodCode: 'EXPRESS', methodName: 'Express', serviceLevel: 'Configured service', amountMinor: 200, currency: 'NGN' }] }] };
describe('shipping checkout selection', () => {
  it('groups options by store and submits only selected identifiers for an authoritative quote', async () => { vi.mocked(api.addresses).mockResolvedValue([address]); vi.mocked(api.shippingOptions).mockResolvedValue(options); vi.mocked(api.quote).mockResolvedValue({ currency: 'NGN', lines: [], shippingSelections: [], subtotalMinor: 1000, discountMinor: 0, shippingMinor: 300, taxMinor: 0, totalMinor: 1300, shippingAddress: address, billingAddress: address }); render(<MemoryRouter><Checkout /></MemoryRouter>); expect(await screen.findByText(/delivery from store a/i)).toBeInTheDocument(); expect(screen.getByRole('button', { name: /refresh authoritative quote/i })).toBeDisabled(); fireEvent.click(screen.getByLabelText(/standard/i)); fireEvent.click(screen.getByLabelText(/express/i)); fireEvent.click(screen.getByRole('button', { name: /refresh authoritative quote/i })); await waitFor(() => expect(api.quote).toHaveBeenCalledWith({ shippingAddressId: 'a1', shippingSelections: [{ storeId: 'store-a', shippingRateId: 'rate-a' }, { storeId: 'store-b', shippingRateId: 'rate-b' }] })); expect(await screen.findByText(/₦13\.00|NGN/i)).toBeInTheDocument(); });
  it('shows an unavailable shipping error without offering a zero-shipping checkout', async () => { vi.mocked(api.addresses).mockResolvedValue([address]); vi.mocked(api.shippingOptions).mockRejectedValue(new Error('Shipping is not available for one or more stores at this destination.')); render(<MemoryRouter><Checkout /></MemoryRouter>); expect(await screen.findByRole('alert')).toHaveTextContent(/shipping is not available/i); expect(screen.queryByRole('button', { name: /place order/i })).not.toBeInTheDocument(); });
});
