import { beforeEach, describe, expect, it, vi } from 'vitest';
import { api, setAccessToken } from './api';

const ok = (data: unknown) => new Response(JSON.stringify({ data }), { status: 200 });
const fail = (status: number, code: string, detail: string) => new Response(JSON.stringify({ code, detail }), { status });

describe('customer API contracts', () => {
  beforeEach(() => { setAccessToken(null); vi.restoreAllMocks(); });
  it('handles registration and login success/failure', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => String(input).endsWith('/auth/login') ? ok({ accessToken: 'a', expiresIn: 900, user: {} }) : ok({ userId: 'u1' })); await expect(api.register({ email: 'a@example.com' })).resolves.toMatchObject({ userId: 'u1' }); await expect(api.login({ email: 'a@example.com', password: 'Password123' })).resolves.toMatchObject({ accessToken: 'a' }); expect(fetchMock).toHaveBeenCalledTimes(2); fetchMock.mockResolvedValueOnce(fail(401, 'UNAUTHENTICATED', 'Invalid email or password.')); await expect(api.login({ email: 'a@example.com', password: 'bad' })).rejects.toMatchObject({ status: 401, code: 'UNAUTHENTICATED' }); });
  it('handles email verification success and expiry errors', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(ok({ id: 'u1' })).mockResolvedValueOnce(fail(400, 'INVALID_OR_EXPIRED_TOKEN', 'The verification link is invalid or expired.')); await expect(api.verifyEmail('valid-token')).resolves.toMatchObject({ id: 'u1' }); await expect(api.verifyEmail('expired-token')).rejects.toMatchObject({ status: 400, code: 'INVALID_OR_EXPIRED_TOKEN' }); expect(fetchMock).toHaveBeenCalledTimes(2); });
  it('builds supported catalog search and filter requests', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(ok([])); await api.products('q=phone&category=electronics&brand=samsung&limit=24'); expect(String(fetchMock.mock.calls[0][0])).toContain('q=phone&category=electronics&brand=samsung&limit=24'); });
  it('handles catalog not-found and server errors', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValueOnce(fail(404, 'NOT_FOUND', 'Product not found.')).mockResolvedValueOnce(fail(503, 'PROVIDER_UNAVAILABLE', 'Try again later.')); await expect(api.product('missing')).rejects.toMatchObject({ status: 404, code: 'NOT_FOUND' }); await expect(api.products()).rejects.toMatchObject({ status: 503, code: 'PROVIDER_UNAVAILABLE' }); });
  it('supports anonymous-compatible cart CRUD, merge recovery, and stock errors', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(ok({ items: [] })); await api.addCartItem('variant', 2); await api.updateCartItem('item', 3); await api.removeCartItem('item'); await api.mergeCart(); await api.recoveryCart(); await api.updateRecoveryCartItem('item', 2); await api.removeRecoveryCartItem('item'); expect(fetchMock).toHaveBeenCalledTimes(7); expect(String(fetchMock.mock.calls[3]?.[0])).toMatch(/\/cart\/merge$/); expect(String(fetchMock.mock.calls[4]?.[0])).toMatch(/\/cart\/recovery$/); fetchMock.mockResolvedValue(fail(422, 'INSUFFICIENT_INVENTORY', 'Not enough stock.')); await expect(api.addCartItem('variant', 2)).rejects.toMatchObject({ status: 422, code: 'INSUFFICIENT_INVENTORY' }); });
  it('initializes payments with a provider and idempotency key but no client amount', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(ok({ id: 'p1', status: 'PENDING', authorizationUrl: 'https://paystack.test' })); await api.createPayment('order-1', 'attempt-123456789'); const request = fetchMock.mock.calls[0][1]!; expect(new Headers(request.headers).get('Idempotency-Key')).toBe('attempt-123456789'); expect(JSON.parse(String(request.body))).toEqual({ provider: 'PAYSTACK' }); });
});
