output "name_prefix" { value = local.name_prefix }
output "resource_names" { value = local.names }
output "common_tags" { value = local.common_tags }
output "aws_region" { value = var.aws_region }
output "vpc_id" { value = aws_vpc.staging.id }
output "public_subnet_ids" { value = [for az in var.availability_zones : aws_subnet.public[az].id] }
output "app_subnet_ids" { value = [for az in var.availability_zones : aws_subnet.app[az].id] }
output "data_subnet_ids" { value = [for az in var.availability_zones : aws_subnet.data[az].id] }
output "alb_security_group_id" { value = aws_security_group.alb.id }
output "api_security_group_id" { value = aws_security_group.api.id }
output "database_security_group_id" { value = aws_security_group.database.id }
output "public_route_table_id" { value = aws_route_table.public.id }
output "app_route_table_id" { value = aws_route_table.app.id }
output "data_route_table_id" { value = aws_route_table.data.id }
output "database_subnet_group_name" { value = aws_db_subnet_group.staging.name }
output "database_endpoint" { value = aws_db_instance.staging.address }
output "database_port" { value = aws_db_instance.staging.port }
output "database_name" { value = aws_db_instance.staging.db_name }
output "database_master_secret_arn" { value = try(aws_db_instance.staging.master_user_secret[0].secret_arn, null) }
output "ecr_repository_url" { value = aws_ecr_repository.backend.repository_url }
output "ecs_cluster_name" { value = aws_ecs_cluster.staging.name }
output "api_task_definition_arn" { value = aws_ecs_task_definition.api.arn }
output "migration_task_definition_arn" { value = aws_ecs_task_definition.migration.arn }
output "api_log_group_name" { value = aws_cloudwatch_log_group.api.name }
output "migration_log_group_name" { value = aws_cloudwatch_log_group.migration.name }
output "ecs_execution_role_arn" { value = aws_iam_role.execution.arn }
output "api_task_role_arn" { value = aws_iam_role.api_task.arn }
output "migration_task_role_arn" { value = aws_iam_role.migration_task.arn }
output "alb_arn" { value = aws_lb.staging.arn }
output "alb_dns_name" { value = aws_lb.staging.dns_name }
output "api_target_group_arn" { value = aws_lb_target_group.api.arn }
output "https_listener_arn" { value = try(aws_lb_listener.https[0].arn, null) }
output "staging_hostname" { value = var.domain_name != "" ? var.domain_name : aws_lb.staging.dns_name }
output "github_oidc_provider_arn" { value = aws_iam_openid_connect_provider.github.arn }
output "github_deployment_role_arn" { value = aws_iam_role.github_deploy.arn }
