import { Router, type NextFunction, type Request, type Response } from 'express';
import type { AuthService } from '../../identity/application/AuthService.js';
import { requireAuthentication, requirePermission } from '../../../shared/presentation/auth.js';
import { AppError } from '../../../shared/domain/AppError.js';
import type { ReturnsService } from '../application/ReturnsService.js';
import { returnCreateSchema, returnUpdateSchema } from './returns.schemas.js';
const asyncRoute = (handler: (req: Request, res: Response) => Promise<void>) => (req: Request, res: Response, next: NextFunction): void => { void handler(req, res).catch(next); };
const param = (value: string | string[] | undefined): string => { if (typeof value !== 'string' || !value) throw new AppError(400, 'VALIDATION_ERROR', 'A route parameter is required.'); return value; };
export function createReturnsRouter(authService: AuthService, service: ReturnsService): Router { const router = Router(); router.use(requireAuthentication(authService)); router.post('/orders/:orderId/returns', asyncRoute(async (req, res) => { const body = returnCreateSchema.parse(req.body); res.status(201).json({ data: await service.create(req.principal!.userId, param(req.params.orderId), body.reasonCode, body.items, body.note) }); })); router.get('/returns', asyncRoute(async (req, res) => { res.json({ data: await service.list(req.principal!.userId) }); })); router.get('/returns/:returnId', asyncRoute(async (req, res) => { res.json({ data: await service.get(req.principal!.userId, param(req.params.returnId)) }); })); return router; }
export function createAdminReturnsRouter(authService: AuthService, service: ReturnsService): Router { const router = Router(); router.use(requireAuthentication(authService), requirePermission('return:manage')); router.get('/returns', asyncRoute(async (_req, res) => { res.json({ data: await service.adminList() }); })); router.patch('/returns/:returnId', asyncRoute(async (req, res) => { const body = returnUpdateSchema.parse(req.body); res.json({ data: await service.adminUpdate(param(req.params.returnId), body.status, body.resolutionCode, body.note) }); })); router.post('/returns/:returnId/refund', asyncRoute(async (req, res) => { const key = req.header('idempotency-key'); if (!key || key.length < 16) throw new AppError(400, 'VALIDATION_ERROR', 'A valid Idempotency-Key header is required.'); res.status(202).json({ data: await service.refund(param(req.params.returnId), key) }); })); return router; }
